name: blah

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  pull_request_target:
    branches: [ "master" ]
    types: [ closed ]
    
jobs:
  divebuild:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test step1
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "event_name: ${{ github.event_name }}, action: ${{ github.event.action }}"
  push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps: 
      - name: test step2
        run: echo "${{ toJson(github.event.pull_request) }} hello"
