name: blah

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  divebuild:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test step1
        run: echo ${{ toJson(github.event) }} 'hi'
      - name: test step2
        if: github.event.pull_request.merged
        run: echo ${{github.event.pull_request}} 'hello'
