name: KVS Docker Image CI

#this trigger will initiate the dive action
on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  divebuild:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test step
        if: github.event.pull_request.merged == true
        run: echo {{github.event}} 'hello'
