name: blah

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [ closed ]
    
jobs:
  divebuild:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: test step1
        run: |
          echo "event_name: ${{ github.event_name }}, action: ${{ github.event.action }}"
      - name: test step2
        if: github.event.pull_request.merged
        run: echo "request merged"
